# Now we will just classify the text ->

In [2]:
import pandas as pd
books = pd.read_csv("books_cleaned.csv")

In [3]:
books["categories"].value_counts().reset_index()

                     categories  count
0                       Fiction   2415
1              Juvenile Fiction    503
2     Biography & Autobiography    371
3                       History    245
4            Literary Criticism    149
..                          ...    ...
508                  Meditation      1
509                     Gay men      1
510           Christian fiction      1
511  Napoleonic Wars, 1800-1815      1
512     Indic fiction (English)      1

[513 rows x 2 columns]

In [4]:
books["categories"].value_counts().reset_index().query("count > 50")

                   categories  count
0                     Fiction   2415
1            Juvenile Fiction    503
2   Biography & Autobiography    371
3                     History    245
4          Literary Criticism    149
5     Comics & Graphic Novels    140
6                  Philosophy    139
7                    Religion    133
8                       Drama    111
9         Juvenile Nonfiction     99
10                     Poetry     67
11       Literary Collections     64
12                    Science     64
13       Business & Economics     59
14             Social Science     56

In [5]:
books[books["categories"] == "Juvenile Fiction"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
32,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,Ocean Star Express,9780006646006 Joe and his parents are enjoyin...
88,9780020442608,0020442602,The voyage of the Dawn Treader,Clive Staples Lewis,Juvenile Fiction,http://books.google.com/books/content?id=fDD3C...,"The ""Dawn Treader"" is the first ship Narnia ha...",1970.0,4.09,216.0,2869.0,The voyage of the Dawn Treader,"9780020442608 The ""Dawn Treader"" is the first..."
96,9780030547744,0030547741,Where the Red Fern Grows,Wilson Rawls,Juvenile Fiction,http://books.google.com/books/content?id=IHpRw...,A young boy living in the Ozarks achieves his ...,2000.0,4.37,288.0,95.0,Where the Red Fern Grows - The Story of Two Do...,9780030547744 A young boy living in the Ozark...
97,9780060000141,0060000147,Poppy's Return,Avi,Juvenile Fiction,http://books.google.com/books/content?id=XbcMJ...,"There's trouble at Gray House, the girlhood ho...",2006.0,3.99,256.0,1086.0,Poppy's Return,"9780060000141 There's trouble at Gray House, ..."
98,9780060001537,0060001534,Diary of a Spider,Doreen Cronin,Juvenile Fiction,http://books.google.com/books/content?id=UWvZo...,This is the diary ... of a spider. But don't b...,2005.0,4.25,40.0,7903.0,Diary of a Spider,9780060001537 This is the diary ... of a spid...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5835,9781596792500,1596792507,Sherlock Holmes and the Case of the Hound of t...,Arthur Conan Doyle;Malvina G. Vogel,Juvenile Fiction,http://books.google.com/books/content?id=EWgWP...,Sherlock Holmes and Dr. Watson travel to the b...,2005.0,4.51,237.0,28.0,Sherlock Holmes and the Case of the Hound of t...,9781596792500 Sherlock Holmes and Dr. Watson ...
5849,9781599900056,159990005X,The Drift House,Dale Peck,Juvenile Fiction,http://books.google.com/books/content?id=kbwPY...,Sent to stay with their uncle in a ship-like h...,2006.0,3.64,437.0,595.0,The Drift House - The First Voyage,9781599900056 Sent to stay with their uncle i...
5922,9781844580514,1844580512,Attack of the Jaguar,M. A. Harvey,Juvenile Fiction,http://books.google.com/books/content?id=3HUdt...,This training manual for operatives of Xtreme ...,2004.0,3.40,125.0,4.0,Attack of the Jaguar,9781844580514 This training manual for operat...
6070,9781930900240,1930900244,The Brothers Lionheart,Astrid Lindgren;Ilon Wikland;Jill Morgan,Juvenile Fiction,http://books.google.com/books/content?id=z2QJA...,Two brothers share many adventures after their...,2004.0,4.36,231.0,19745.0,The Brothers Lionheart,9781930900240 Two brothers share many adventu...
6095,9781932416374,1932416374,The Very Persistent Gappers of Frip,George Saunders;Lane Smith,Juvenile Fiction,http://books.google.com/books/content?id=xYJOP...,A novel set in the seaside village of Frip fol...,2006.0,4.11,84.0,2317.0,The Very Persistent Gappers of Frip,9781932416374 A novel set in the seaside vill...

In [6]:
books[books["categories"] == "Juvenile Nonfiction"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
122,9780060277406,0060277408,The Secret Garden Cookbook,Amy Cotler,Juvenile Nonfiction,http://books.google.com/books/content?id=c7E_H...,Frances Hodgson Burnett's The Secret Garden de...,1999.0,4.28,128.0,142.0,The Secret Garden Cookbook - Recipes Inspired ...,9780060277406 Frances Hodgson Burnett's The S...
123,9780060278427,0060278420,Laura's Album,William Anderson,Juvenile Nonfiction,http://books.google.com/books/content?id=_zTkq...,Though best known as the author of the Little ...,1998.0,4.30,80.0,713.0,Laura's Album - A Remembrance Scrapbook of Lau...,9780060278427 Though best known as the author...
247,9780060782139,0060782137,Time For Kids: Butterflies!,Editors of TIME For Kids,Juvenile Nonfiction,http://books.google.com/books/content?id=OdZxn...,"Butterflies There are 20,000 different kinds o...",2006.0,4.00,32.0,20.0,Time For Kids: Butterflies!,"9780060782139 Butterflies There are 20,000 di..."
287,9780060882600,0060882603,The Annotated Charlotte's Web,E. B. White,Juvenile Nonfiction,http://books.google.com/books/content?id=vaYYH...,"Charlotte's Web, one of America's best-loved c...",2006.0,4.16,320.0,41.0,The Annotated Charlotte's Web,"9780060882600 Charlotte's Web, one of America..."
477,9780064462044,0064462048,My Little House Crafts Book,Carolyn Strom Collins,Juvenile Nonfiction,http://books.google.com/books/content?id=lTzrs...,Make the same pioneer crafts that Laura did! I...,1998.0,4.05,64.0,56.0,My Little House Crafts Book - 18 Projects from...,9780064462044 Make the same pioneer crafts th...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5671,9781585361618,1585361615,O Is for Old Dominion,Pamela Duncan Edwards;Troy Howell,Juvenile Nonfiction,http://books.google.com/books/content?id=TgsEA...,"Explores the heritage and history of Virginia,...",2005.0,3.75,40.0,19.0,O Is for Old Dominion - A Virginia Alphabet,9781585361618 Explores the heritage and histo...
5698,9781586853334,1586853333,The Big Book of Boy Stuff,Bart King,Juvenile Nonfiction,http://books.google.com/books/content?id=08Ilm...,There's this boy. Let's say he's somewhere bet...,2004.0,4.24,292.0,141.0,The Big Book of Boy Stuff,9781586853334 There's this boy. Let's say he'...
5955,9781857232097,1857232097,The Fires of Heaven,Robert Jordan,Juvenile Nonfiction,http://books.google.com/books/content?id=4HyfQ...,The fifth book in Robert Jordan's internationa...,1994.0,4.15,912.0,106302.0,The Fires of Heaven,9781857232097 The fifth book in Robert Jordan...
6076,9781931414166,1931414165,The Brooklyn Bridge,Elizabeth Mann;Alan Witschonke,Juvenile Nonfiction,http://books.google.com/books/content?id=s28MA...,Describes the construction of the Brooklyn Bri...,2006.0,4.44,46.0,35.0,The Brooklyn Bridge,9781931414166 Describes the construction of t...
6128,9783791329284,3791329286,Joseph Cornell,Joseph Cornell;Alison Baverstock,Juvenile Nonfiction,http://books.google.com/books/content?id=KnO8A...,Provides an introduction to the American artis...,2003.0,4.06,27.0,31.0,Joseph Cornell - Secrets in a Box,9783791329284 Provides an introduction to the...

In [7]:
# Now, mapping over the categories to create a new column called "category_type" that will have the value "Juvenile" for both "Juvenile Fiction" and "Juvenile Nonfiction", and "Other" for all other categories.
category_mapping = {
        'Fiction':"Fiction",
        'Juvenile Fiction':"Juvenile Fiction",
        'Biography & Autobiography': "Nonfiction",
        'History': "Nonfiction",
        'Philosophy':"Nonfiction",
        'Religion':"Nonfiction",
        'Comics & Graphic Novels':"Fiction",
        'Drama': "Fiction",
        'Juvenile Nonfiction':"Children's Nonfiction",
        'Science':"Nonfiction",
        'Poetry':"Fiction"
}
books["simple_categories"] = books["categories"].map(category_mapping)
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critic...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web - A Novel,9780002261982 A new 'Christie for Christmas' ...,NaN
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroin...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lo...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. L...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6139,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a m...,NaN
6140,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Pass...,NaN
6141,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that - Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless...,Nonfiction
6142,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition ...,Nonfiction
6143,9789042003408,9042003405,'I'm Telling You Stories',Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0,'I'm Telling You Stories' - Jeanette Winterson...,9789042003408 This is a jubilant and rewardin...,NaN

In [8]:
# Now seeing how many books does not have the fiction or nonfiction category.
books[~(books["simple_categories"].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critic...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroin...",Fiction
9,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,2966.0,Warhost of Vastmark,9780006482079 Tricked once more by his wily h...,Fiction
32,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,Ocean Star Express,9780006646006 Joe and his parents are enjoyin...,Juvenile Fiction
49,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlx...,A Few Weeks After Marrying An Attractive Young...,2002.0,3.71,352.0,8852.0,Taken at the Flood,9780007121014 A Few Weeks After Marrying An A...,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6128,9783791329284,3791329286,Joseph Cornell,Joseph Cornell;Alison Baverstock,Juvenile Nonfiction,http://books.google.com/books/content?id=KnO8A...,Provides an introduction to the American artis...,2003.0,4.06,27.0,31.0,Joseph Cornell - Secrets in a Box,9783791329284 Provides an introduction to the...,Children's Nonfiction
6134,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,Rescued from the lockers in which they were le...,2002.0,3.75,393.0,5560.0,Coin Locker Babies,9784770028969 Rescued from the lockers in whi...,Fiction
6135,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a you...,Fiction
6141,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that - Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless...,Nonfiction
6142,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition ...,Nonfiction

In [9]:
# using the zero-shot-classification pipleline to classify the books that do not have a category.
from transformers import pipeline
fiction_categories = ["Fiction","Nonfiction"]
pipe = pipeline("zero-shot-classification",
                      model="facebook/bart-large-mnli",
                      device="mps"
                      )

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

In [10]:
sequence = books.loc[books["simple_categories"]== "Fiction","description"].reset_index(drop=True)[0]

In [11]:
pipe(sequence,fiction_categories)

{'sequence': 'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.',
 'labels': ['Fiction', 'Nonfiction'],
 'scores': [0.8438267111778259, 0.15617327392101288]}

In [12]:
import numpy as np
max_index = np.argmax(pipe(sequence,fiction_categories)["scores"])
max_label = pipe(sequence,fiction_categories)["labels"][max_index]
max_label

'Fiction'

In [13]:
def generate_predictions(sequence,categories):
        predictions = pipe(sequence,categories)
        max_index = np.argmax(predictions["scores"])
        max_label = predictions["labels"][max_index]
        return max_label

In [14]:
from tqdm import tqdm # the loop is taking a long time to run so we will use tqdm to show the progress of the loop.
actual_categories = []
predict_categories = []
# This is for the fiction category.
for i in tqdm(range(0,300)):
        sequence = books.loc[books["simple_categories"] == "Fiction","description"].reset_index(drop=True)[i]
        predict_categories += [generate_predictions(sequence,fiction_categories)]
        actual_categories += ["Fiction"]

100%|██████████| 300/300 [02:40<00:00,  1.87it/s]

In [15]:
# This is for the non-fiction category.
for i in tqdm(range(0,300)):
        sequence = books.loc[books["simple_categories"] == "Nonfiction","description"].reset_index(drop=True)[i]
        predict_categories += [generate_predictions(sequence,fiction_categories)]
        actual_categories += ["Nonfiction"]

100%|██████████| 300/300 [02:45<00:00,  1.82it/s]

In [16]:
prediction_df = pd.DataFrame({"actual_categories":actual_categories,"predict_categories":predict_categories})

In [17]:
prediction_df

    actual_categories predict_categories
0             Fiction            Fiction
1             Fiction            Fiction
2             Fiction            Fiction
3             Fiction         Nonfiction
4             Fiction            Fiction
..                ...                ...
595        Nonfiction            Fiction
596        Nonfiction         Nonfiction
597        Nonfiction         Nonfiction
598        Nonfiction         Nonfiction
599        Nonfiction            Fiction

[600 rows x 2 columns]

In [18]:
# Now, we are able to compare the actual categories with the predicted categories to see how well our model is performing. 
# Now, we will make a column to see compare results.
prediction_df["correct_prediction"] = (np.where(prediction_df["actual_categories"]==prediction_df["predict_categories"],1,0))

In [19]:
prediction_df["correct_prediction"].sum() / len(prediction_df)
# The model is performing well with an accuracy of 78%.

np.float64(0.78)

In [20]:
isbns = []
predicted_cats = []
missing_cats = books.loc[books["simple_categories"].isna(),["isbn13","description"]].reset_index(drop=True)

In [21]:
for i in tqdm(range(0, len(missing_cats))):
        sequence = missing_cats["description"][i]
        predicted_cats += [generate_predictions(sequence,fiction_categories)]
        isbns += [missing_cats["isbn13"][i]]

100%|██████████| 1857/1857 [18:18<00:00,  1.69it/s]

In [22]:
missing_prediction_df = pd.DataFrame({"isbn13":isbns,"predicted_categories":predicted_cats})

In [23]:
missing_prediction_df

             isbn13 predicted_categories
0     9780002261982              Fiction
1     9780006280897           Nonfiction
2     9780006280934           Nonfiction
3     9780006380832           Nonfiction
4     9780006470229              Fiction
...             ...                  ...
1852  9788171565641              Fiction
1853  9788172235222              Fiction
1854  9788173031014           Nonfiction
1855  9788179921623              Fiction
1856  9789042003408           Nonfiction

[1857 rows x 2 columns]

In [31]:
# now joining this data frame to the books data frame.
books = pd.merge(books,missing_prediction_df,on="isbn13",how="left")
books["simple_categories"] = np.where(books["simple_categories"].isna(),books["predicted_categories"],books["simple_categories"])
books = books.drop(columns=["predicted_categories"], errors="ignore")

In [32]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories,predicted_categories_x,predicted_categories_y
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critic...,Fiction,NaN,NaN
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web - A Novel,9780002261982 A new 'Christie for Christmas' ...,Fiction,Fiction,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroin...",Fiction,NaN,NaN
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lo...,Nonfiction,Nonfiction,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. L...",Nonfiction,Nonfiction,Nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6139,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a m...,Nonfiction,Nonfiction,Nonfiction
6140,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Pass...,Fiction,Fiction,Fiction
6141,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that - Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless...,Nonfiction,NaN,NaN
6142,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition ...,Nonfiction,NaN,NaN
6143,9789042003408,9042003405,'I'm Telling You Stories',Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0,'I'm Telling You Stories' - Jeanette Winterson...,9789042003408 This is a jubilant and rewardin...,Nonfiction,Nonfiction,Nonfiction

In [36]:
books[books["categories"].str.lower().isin([
        "romance",
        "science fiction",
        "sci-fi",
        "fantasy",
        "horror",
        "mystery",
        "thriller",
        "comedy",
        "drama",
        "crime",
        "mystery",
        "historical"
])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories,predicted_categories_x,predicted_categories_y
25,9780006513087,0006513085,Gravity,Tess Gerritsen,Science fiction,http://books.google.com/books/content?id=KI66c...,Emma Watson a research physician has been trai...,2004.0,4.04,342.0,8024.0,Gravity,9780006513087 Emma Watson a research physicia...,Nonfiction,Nonfiction,Nonfiction
519,9780099410355,0099410354,Traitor,Matthew Woodring Stover,Science fiction,http://books.google.com/books/content?id=VbICO...,"From the depths of catastrophe, a glimmer of h...",2002.0,4.00,320.0,6765.0,Traitor,"9780099410355 From the depths of catastrophe,...",Fiction,Fiction,Fiction
522,9780099422341,0099422344,Yeats is Dead!,Joseph O'Connor,Comedy,http://books.google.com/books/content?id=DrE3I...,"In aid of Amnesty International, this is a bri...",2002.0,3.39,298.0,34.0,Yeats is Dead! - A Novel by Fifteen Irish Writers,9780099422341 In aid of Amnesty International...,Fiction,Fiction,Fiction
535,9780099446729,0099446723,Blackwood Farm,Anne Rice,Horror,http://books.google.com/books/content?id=cIn8T...,"Lestat Is Back, Saviour And Demon, Presiding O...",2003.0,3.86,774.0,26145.0,Blackwood Farm,"9780099446729 Lestat Is Back, Saviour And Dem...",Fiction,Fiction,Fiction
646,9780140189223,014018922X,Six Characters in Search of an Author and Othe...,Luigi Pirandello,Drama,http://books.google.com/books/content?id=AU4Mc...,"Accompanied by two additional plays, presents ...",1995.0,3.95,224.0,2888.0,Six Characters in Search of an Author and Othe...,9780140189223 Accompanied by two additional p...,Fiction,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5954,9781857231359,185723135X,Use of Weapons,Iain Banks,Science fiction,NaN,The man known as Cheradenine Zakalwe was one o...,1992.0,4.19,411.0,30779.0,Use of Weapons,9781857231359 The man known as Cheradenine Za...,Nonfiction,Nonfiction,Nonfiction
5971,9781857989342,1857989341,The Gods Themselves,Isaac Asimov,Science fiction,http://books.google.com/books/content?id=8ClIP...,"In the year 2100, mankind on Earth, settlers i...",2000.0,4.09,288.0,41304.0,The Gods Themselves,"9781857989342 In the year 2100, mankind on Ea...",Fiction,Fiction,Fiction
6053,9781904271062,1904271065,King Henry IV Part 2,William Shakespeare;A. R. Humphreys,Drama,http://books.google.com/books/content?id=AG4h-...,A. R. Humphreyswas Professor of English at Lei...,1967.0,3.80,336.0,241.0,King Henry IV Part 2 - Second Series,9781904271062 A. R. Humphreyswas Professor of...,Fiction,NaN,NaN
6054,9781904271352,1904271359,King Henry IV Part 1,William Shakespeare;David Scott Kastan,Drama,http://books.google.com/books/content?id=7ioeG...,"Shakespeare's rich exploration of kingship, po...",2002.0,3.82,398.0,17063.0,King Henry IV Part 1 - Third Series,9781904271352 Shakespeare's rich exploration ...,Fiction,NaN,NaN
6055,9781904271550,1904271553,Hamlet: The Texts of 1603 and 1623,William Shakespeare,Drama,http://books.google.com/books/content?id=rGFlA...,This second volume gives readers the First Qua...,2006.0,4.01,384.0,16.0,Hamlet: The Texts of 1603 and 1623 - Third Series,9781904271550 This second volume gives reader...,Fiction,NaN,NaN

In [37]:
books.to_csv("books_with_categories.csv",index=False)